### ISSUE TITLE
Where is original Qt app?

### ISSUE THREAD

**Issue by ghost** [tompaana/compass-wp#1]
Can you give a link where original Qt app exist?

Related:
- http://freesoftware-anique.blogspot.com/2011/05/compass-v10-s60v53.html
- http://mosh.ph/26058/dragon-sight-compass-v1-100-s3-unsigned
- http://www.androidfreeware.net/download-orienteer.html
- https://itunes.apple.com/us/app/orienteering-compass/id372749402?mt=8

**Comment by tompaana** [comment]
Hi,

Here: https://github.com/microsoft-mobile/compass-qt

Cheers,
Tomi
